name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [linuxmint.18.3-x64, win10-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Publish (${{ matrix.runtime }})
        run: dotnet publish Imdb.sln -c 'Release' -r '${{ matrix.runtime }}' -v 'normal' --self-contained true -p:PublishTrimmed=true -p:TrimMode=Link -p:Version=1.0.0.0

      - name: Upload artifacts (${{ matrix.runtime }})
        uses: actions/upload-artifact@v2
        with:
          name: Imdb.Loader_${{ matrix.runtime }}
          path: Imdb.Loader/bin/Release/net5.0/win10-x64/publish/
