name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      version: 1.0.0.0
    strategy:
      matrix:
        runtime: [linuxmint.18.3-x64, win10-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet publish Imdb.sln -c 'Release' -r '${{ matrix.runtime }}' -v 'normal' --self-contained true -p:PublishTrimmed=true -p:TrimMode=Link -p:PublishReadyToRun=false -p:PublishReadyToRunShowWarnings=false -p:Version=${{ env.version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Imdb.Loader_${{ matrix.runtime }}_${{ env.version }}
          path: Imdb.Loader/bin/Release/net5.0/${{ matrix.runtime }}/publish/
