name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Publish (Windows 10 x64)
        run: dotnet publish Imdb.sln -c 'Release' -r 'win10-x64' -v 'normal' --self-contained true -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true -p:PublishTrimmed=true -p:TrimMode=Link

      - name: Upload artifacts (Windows 10 x64)
        uses: actions/upload-artifact@v2
        with:
          name: Imdb.Loader
          path: Imdb.Loader/bin/Release/net5.0/win10-x64/publish/
